global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
    basic_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:8080"]